name: Bug report
description: Report something that is broken or incorrect
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Before you post this issue, please check the documentation:

        <https://ccbr.github.io/CCBR/MOSuite-Galaxy>

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: command_used
    attributes:
      label: Command used and output
      description: Steps to reproduce the behaviour. Please paste the code you used or describe what you were doing in the GUI. Paste screenshots of the Galaxy GUI if possible.
      render: console
      placeholder: |
        Describe the steps, including screenshots if using the Galaxy GUI.

  - type: textarea
    id: files
    attributes:
      label: Relevant files
      description: |
        Please drag and drop any relevant files here. If running on galaxy, please include any logs, cleaned_params.json, or output dataset files. Create a `.zip` archive if the extension is not allowed.

  - type: textarea
    id: system
    attributes:
      label: System information
      description: |
        - Version of MOSuite on Galaxy _(eg. 52, 53)_
