# adapted from https://github.com/rstudio/vetiver-python/blob/main/.github/workflows/docs.yml
name: "docs"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  release:
    types: [published]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.14
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs/ # where the qmd documents are
        env:
          GITHUB_TOKEN: ${{ github.token }}
